# Generated by Django 3.2.4 on 2021-06-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_work_contributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='contributions',
        ),
    ]
