# Generated by Django 3.2.4 on 2021-06-11 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_work_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='contributions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default='{"hello"}', size=None),
            preserve_default=False,
        ),
    ]
