# Generated by Django 3.2.4 on 2021-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_work_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client',
            field=models.CharField(default='Emmanuel', max_length=500),
            preserve_default=False,
        ),
    ]
